python src/run_summarization.py \
--output_dir ./out/vanilla \
--model_name kssteven/T5-large-xsum \
--tokenizer_name google-t5/t5-small \
--dataset_name xsum \
--source_prefix "summarize: " \
--num_beam 1 \
--evaluation_strategy epoch --save_strategy epoch \
--do_eval \
--per_device_eval_batch_size 1 \
--predict_with_generate
